task_name: "Davidson2017"
train_file_path: "./dataset/Davidson2017/labeled_data.csv"
test_file_path: ""
output_path: "./outputs"
text_idx: 6
class_idx: 5
delimiter: ","
test_split: 0.1

model_name: "vinai/bertweet-base"
label_maps: {"0": 1, "1": 1, "2": 0} #0-hate speech; 1-offensive language; 2-neither
train_batch_size: 32
test_batch_size: 16
kfold: 5
max_length: 128
use_gpu: True
weight_decay: 0.0
learning_rate: 0.00001
num_epochs: 10
random_state: 42
early_stop: 2